services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devfest-recap-app
    ports:
      - "1923:1923"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - devtv_net
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: devfest-recap-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "3924:5432"
    volumes:
      - ./logs:/logs
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: devfest-recap-redis
    ports:
      - "8389:6379"
    volumes:
      - ./logs:/logs
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  default:
  devtv_net:
    external: true
    name: devtv_devtv-net
